/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-09 07:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spareparts.sparepartsModel;

public final class H_005fAdminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.spareparts.sparepartsModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");

sparepartsModel admin = (sparepartsModel) session.getAttribute("admin");

    if (admin == null) {
        response.sendRedirect("AdminLogin.jsp");
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Dashboard</title>\n");
      out.write("    <!-- Link to external CSS -->\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <link rel=\"icon\" href=\"Assets/icon.png\" type=\"image/x-icon\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/H_AdminDashboard.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function logout() {\n");
      out.write("            \n");
      out.write("            window.location.href = \"logout\"; \n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bg-gradient\">\n");
      out.write("\n");
      out.write("    <!-- Side Navigation -->\n");
      out.write("    <div class=\"flex-container\">\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"sidebar-header\">\n");
      out.write("                <i class=\"fas fa-user-cog\"></i>\n");
      out.write("                <span>Admin Panel</span>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"sidebar-links\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"H_AdminDashboard.jsp\">\n");
      out.write("                        <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("                        <span>Dashboard</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"H_ManageUser.jsp\">\n");
      out.write("                        <i class=\"fas fa-users\"></i>\n");
      out.write("                        <span>Users</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"getAllPartsServlet\">\n");
      out.write("                        <i class=\"fas fa-cogs\"></i>\n");
      out.write("                        <span>Spare Parts</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Content Area -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <!-- Top Bar -->\n");
      out.write("            <div class=\"bg-white shadow-md px-6 py-4 flex justify-between items-center\">\n");
      out.write("                <div class=\"flex items-center space-x-4\">\n");
      out.write("                    <span class=\"font-semibold text-xl\">Admin Dashboard</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"flex items-center space-x-4\">\n");
      out.write("                    <!-- Admin Profile Picture and Name -->\n");
      out.write("                    <div class=\"flex items-center space-x-3\">\n");
      out.write("                        \n");
      out.write("                        <span class=\"text-gray-700 font-medium\">");
      out.print(admin.getName() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <button onclick=\"logout()\" class=\"bg-red-500 text-white px-4 py-2 rounded-full hover:bg-red-600\">\n");
      out.write("				        <i class=\"fas fa-sign-out-alt\"></i> Logout\n");
      out.write("				    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Welcome Section -->\n");
      out.write("            <div class=\"welcome-section\">\n");
      out.write("                <div class=\"welcome-box\">\n");
      out.write("                    <div class=\"decorative-element top-right\"></div>\n");
      out.write("                    <div class=\"decorative-element bottom-left\"></div>\n");
      out.write("                    <div class=\"content\">\n");
      out.write("                        <div class=\"icon-container\">\n");
      out.write("                            <i class=\"fas fa-hand-sparkles\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <h1 class=\"welcome-text\">Welcome, ");
      out.print(admin.getName() );
      out.write("!</h1>\n");
      out.write("                        <div class=\"divider\"></div>\n");
      out.write("                        <p class=\"welcome-message\">We're delighted to have you back. Your dashboard is ready for you to\n");
      out.write("                            manage and monitor your system with ease.</p>\n");
      out.write("                        <div class=\"date-display\">\n");
      out.write("                            <span class=\"date-text\">Today is </span>\n");
      out.write("                            <span id=\"currentDate\" class=\"date-value\"></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Script for displaying the current date -->\n");
      out.write("    <script>\n");
      out.write("        document.getElementById('currentDate').textContent = new Date().toLocaleDateString('en-US', {\n");
      out.write("            weekday: 'long',\n");
      out.write("            year: 'numeric',\n");
      out.write("            month: 'long',\n");
      out.write("            day: 'numeric'\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
