/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-09 07:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class H_005fCreateManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1746611427000L));
    _jspx_dependants.put("jar:file:/Users/hirushadilshan/Desktop/online-vehicle-spareparts-management-system/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/online-vehicle-spareparts-management-system/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Create New Manager Record</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/H_CreateAdmin.css\">\n");
      out.write("    <link rel=\"icon\" href=\"Assets/icon.png\" type=\"image/x-icon\">\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("    <!-- FontAwesome CDN -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function logout() {\n");
      out.write("            \n");
      out.write("            window.location.href = \"logout\"; \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        function logout() {\n");
      out.write("            window.location.href = \"logout\"; \n");
      out.write("        }\n");
      out.write("\n");
      out.write("        \n");
      out.write("        function validateForm(event) {\n");
      out.write("            event.preventDefault(); // Prevent default form submission\n");
      out.write("            \n");
      out.write("            const passwordInput = document.getElementById(\"password\");\n");
      out.write("            const passwordError = document.getElementById(\"passwordError\");\n");
      out.write("            const passwordPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*])[A-Za-z\\d!@#$%^&*]{8,}$/;\n");
      out.write("            \n");
      out.write("            passwordError.textContent = \"\";\n");
      out.write("            \n");
      out.write("            if (!passwordPattern.test(passwordInput.value)) {\n");
      out.write("                passwordError.textContent = \"Password must be at least 8 characters long, include 1 uppercase, 1 lowercase, 1 number, and 1 special character (e.g., !@#$%^&*)\";\n");
      out.write("                passwordInput.focus();\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.querySelector(\"form\").submit();\n");
      out.write("        }\n");
      out.write("    \n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bg-gray-50\">\n");
      out.write("    <div class=\"flex-container\">\n");
      out.write("        <!-- Side Navigation -->\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <div class=\"sidebar-header\">\n");
      out.write("                <i class=\"fas fa-user-cog\"></i>\n");
      out.write("                <span>Admin Panel</span>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"sidebar-links\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"H_AdminDashboard.jsp\">\n");
      out.write("                        <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("                        <span>Dashboard</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"H_ManageUser.jsp\">\n");
      out.write("                        <i class=\"fas fa-users\"></i>\n");
      out.write("                        <span>Users</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"getAllPartsServlet\">\n");
      out.write("                        <i class=\"fas fa-cogs\"></i>\n");
      out.write("                        <span>Spare Parts</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Content Area -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <!-- Top Bar -->\n");
      out.write("            <div class=\"bg-white shadow-md px-6 py-4 flex justify-between items-center\">\n");
      out.write("                <div class=\"flex items-center space-x-4\">\n");
      out.write("                    <span class=\"font-semibold text-xl\">Admin Dashboard</span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"flex items-center space-x-4\">\n");
      out.write("                    <!-- Logout -->\n");
      out.write("                    \n");
      out.write("                    <button onclick=\"logout()\" class=\"bg-red-500 text-white px-4 py-2 rounded-full hover:bg-red-600\">\n");
      out.write("				        <i class=\"fas fa-sign-out-alt\"></i> Logout\n");
      out.write("				    </button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Form with styling -->\n");
      out.write("            <div class=\"form-container\">\n");
      out.write("                <form action=\"createManagerServlet\" method=\"POST\" class=\"form\">\n");
      out.write("\n");
      out.write("                    <div class=\"grid-container\">\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <label for=\"name\">Full Name</label>\n");
      out.write("                            <input type=\"text\" id=\"name\" name=\"name\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    \n");
      out.write("\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <label for=\"email\">Email Address</label>\n");
      out.write("                            <input type=\"email\" id=\"email\" name=\"email\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <label for=\"phone\">Phone Number</label>\n");
      out.write("                            <input type=\"tel\" id=\"phone\" name=\"phonenumber\" required>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        \n");
      out.write("\n");
      out.write("                        <div class=\"input-group\">\n");
      out.write("                            <label for=\"password\">Password</label>\n");
      out.write("                            <input type=\"password\" id=\"password\" name=\"password\" \n");
      out.write("                                   pattern=\"(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*])[A-Za-z\\d!@#$%^&*]{8,}\"\n");
      out.write("                                   title=\"Password must be at least 8 characters long, include 1 uppercase, 1 lowercase, 1 number, and 1 special character (e.g., !@#$%^&*)\"\n");
      out.write("                                   required>\n");
      out.write("                            <span id=\"passwordError\" style=\"color: red; font-size: 0.9em;\"></span>\n");
      out.write("                        </div>\n");
      out.write("                     </div>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                        \n");
      out.write("\n");
      out.write("                    <div class=\"form-footer\">\n");
      out.write("                        <button type=\"submit\" class=\"save-btn\">\n");
      out.write("                            <i class=\"fas fa-save\"></i>\n");
      out.write("                            <span>Save Record</span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /H_CreateManager.jsp(132,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("						    <p style=\"color: red;\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</p>\n");
        out.write("						");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
